const Sellers = require('../../../models/sellersData'); // Import the Meals model


async function populateSellers() {
  const sellersData = [
   {
    name: "Mama's Kitchen",
    email: "mama@example.com",
    phone: "0241234567",
    sellerType: "Business",
    general_rating: 4.5,
    health_rating: 4.2,
    trend_rating: 4.8,
    profileId: "6456a1b2c3d4e5f678901234",
    address: {
      street: "123 Main Street",
      city: "Accra",
      state: "Greater Accra",
      zip: "00233",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Auntie Akos",
    email: "akos@example.com",
    phone: "0249876543",
    sellerType: "Private",
    general_rating: 4.8,
    health_rating: 4.5,
    trend_rating: 4.7,
    profileId: "6456a1b2c3d4e5f678901235",
    address: {
      street: "456 Market Road",
      city: "Kumasi",
      state: "Ashanti",
      zip: "00234",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Tilapia Joint",
    email: "tilapia@example.com",
    phone: "0245678901",
    sellerType: "Business",
    general_rating: 4.2,
    health_rating: 4.0,
    trend_rating: 4.5,
    profileId: "6456a1b2c3d4e5f678901236",
    address: {
      street: "789 Riverside Drive",
      city: "Cape Coast",
      state: "Central",
      zip: "00235",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kenkey House",
    email: "kenkey@example.com",
    phone: "0243456789",
    sellerType: "Business",
    general_rating: 4.0,
    health_rating: 3.8,
    trend_rating: 4.2,
    profileId: "6456a1b2c3d4e5f678901237",
    address: {
      street: "321 Coastal Road",
      city: "Takoradi",
      state: "Western",
      zip: "00236",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Waakye Spot",
    email: "waakye@example.com",
    phone: "0246543210",
    sellerType: "Private",
    general_rating: 4.7,
    health_rating: 4.4,
    trend_rating: 4.9,
    profileId: "6456a1b2c3d4e5f678901238",
    address: {
      street: "654 Food Street",
      city: "Tamale",
      state: "Northern",
      zip: "00237",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Fufu Palace",
    email: "fufu@example.com",
    phone: "0247654321",
    sellerType: "Business",
    general_rating: 4.6,
    health_rating: 4.3,
    trend_rating: 4.7,
    profileId: "6456a1b2c3d4e5f678901239",
    address: {
      street: "987 Palace Avenue",
      city: "Ho",
      state: "Volta",
      zip: "00238",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Banku Delight",
    email: "banku@example.com",
    phone: "0248765432",
    sellerType: "Private",
    general_rating: 4.3,
    health_rating: 4.1,
    trend_rating: 4.5,
    profileId: "6456a1b2c3d4e5f678901240",
    address: {
      street: "321 Banku Lane",
      city: "Sunyani",
      state: "Bono",
      zip: "00239",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Jollof Express",
    email: "jollof@example.com",
    phone: "0249871234",
    sellerType: "Business",
    general_rating: 4.9,
    health_rating: 4.7,
    trend_rating: 4.8,
    profileId: "6456a1b2c3d4e5f678901241",
    address: {
      street: "123 Jollof Street",
      city: "Tema",
      state: "Greater Accra",
      zip: "00240",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Plantain Paradise",
    email: "plantain@example.com",
    phone: "0246549871",
    sellerType: "Private",
    general_rating: 4.4,
    health_rating: 4.2,
    trend_rating: 4.6,
    profileId: "6456a1b2c3d4e5f678901242",
    address: {
      street: "456 Plantain Road",
      city: "Bolgatanga",
      state: "Upper East",
      zip: "00241",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rice Haven",
    email: "rice@example.com",
    phone: "0243219876",
    sellerType: "Business",
    general_rating: 4.8,
    health_rating: 4.5,
    trend_rating: 4.9,
    profileId: "6456a1b2c3d4e5f678901243",
    address: {
      street: "789 Rice Street",
      city: "Wa",
      state: "Upper West",
      zip: "00242",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    // Add more sellers as needed...
  ];

  try {
    await Sellers.insertMany(sellersData);
    console.log("Successfully populated the sellers table with sample data.");
  } catch (error) {
    console.error("Error populating sellers table:", error);
  }
}

module.exports = { populateSellers };