const Meals = require('../../../models/mealData'); // Import the Meals model

async function populateMeals() {
  const ghanaianDishes = [
    {
    name: "Jollof Rice with Chicken",
    description: "A delicious plate of jollof rice served with grilled chicken.",
    price: 30,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Rice", quantity: "2 cups" },
      { name: "Tomatoes", quantity: "3 large" },
      { name: "Chicken", quantity: "500g" },
      { name: "Onions", quantity: "2 medium" },
    ],
    imageUrl: "https://example.com/jollof-chicken.jpg",
    preparationTime: 45,
    calories: 450,
    general_rating: 4.5,
    health_rating: 4.2,
    trend_rating: 4.8,
    tags: ["Spicy", "Popular"],
    sellerType: "Business",
    sellerName: "Mama's Kitchen",
    sellerId: "6456a1b2c3d4e5f678901234",
  },
  {
    name: "Fufu with Light Soup",
    description: "Traditional fufu served with goat meat light soup.",
    price: 35,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Cassava", quantity: "2 pieces" },
      { name: "Plantain", quantity: "2 pieces" },
      { name: "Goat Meat", quantity: "500g" },
      { name: "Tomatoes", quantity: "4 large" },
    ],
    imageUrl: "https://example.com/fufu-light-soup.jpg",
    preparationTime: 60,
    calories: 500,
    general_rating: 4.7,
    health_rating: 4.5,
    trend_rating: 4.6,
    tags: ["Traditional", "Soup"],
    sellerType: "Private",
    sellerName: "Auntie Akos",
    sellerId: "6456a1b2c3d4e5f678901235",
  },
  {
    name: "Grilled Tilapia with Banku",
    description: "Grilled tilapia served with banku and hot pepper sauce.",
    price: 40,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Tilapia", quantity: "1 large" },
      { name: "Corn Dough", quantity: "2 cups" },
      { name: "Cassava Dough", quantity: "1 cup" },
      { name: "Pepper", quantity: "3 pieces" },
    ],
    imageUrl: "https://example.com/banku-tilapia.jpg",
    preparationTime: 50,
    calories: 480,
    general_rating: 4.6,
    health_rating: 4.3,
    trend_rating: 4.7,
    tags: ["Grilled", "Spicy"],
    sellerType: "Business",
    sellerName: "Tilapia Joint",
    sellerId: "6456a1b2c3d4e5f678901236",
  },
  {
    name: "Kenkey with Fried Fish",
    description: "Fermented corn dough served with fried fish and pepper sauce.",
    price: 20,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Corn Dough", quantity: "2 balls" },
      { name: "Fish", quantity: "1 large" },
      { name: "Pepper", quantity: "3 pieces" },
      { name: "Onions", quantity: "1 medium" },
    ],
    imageUrl: "https://example.com/kenkey-fish.jpg",
    preparationTime: 30,
    calories: 350,
    general_rating: 4.4,
    health_rating: 4.0,
    trend_rating: 4.5,
    tags: ["Traditional", "Spicy"],
    sellerType: "Business",
    sellerName: "Kenkey House",
    sellerId: "6456a1b2c3d4e5f678901237",
  },
  {
    name: "Waakye with Fried Plantain",
    description: "Rice and beans served with fried plantain, boiled egg, and meat.",
    price: 25,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Rice", quantity: "2 cups" },
      { name: "Beans", quantity: "1 cup" },
      { name: "Plantain", quantity: "2 pieces" },
      { name: "Egg", quantity: "1 piece" },
    ],
    imageUrl: "https://example.com/waakye-plantain.jpg",
    preparationTime: 40,
    calories: 400,
    general_rating: 4.8,
    health_rating: 4.5,
    trend_rating: 4.9,
    tags: ["Popular", "Vegetarian"],
    sellerType: "Private",
    sellerName: "Waakye Spot",
    sellerId: "6456a1b2c3d4e5f678901238",
  },
  {
    name: "Fufu with Palm Nut Soup",
    description: "Fufu served with palm nut soup and assorted meat.",
    price: 38,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Cassava", quantity: "2 pieces" },
      { name: "Palm Nut", quantity: "1 cup" },
      { name: "Goat Meat", quantity: "500g" },
      { name: "Tomatoes", quantity: "4 large" },
    ],
    imageUrl: "https://example.com/fufu-palmnut.jpg",
    preparationTime: 70,
    calories: 520,
    general_rating: 4.6,
    health_rating: 4.4,
    trend_rating: 4.7,
    tags: ["Traditional", "Soup"],
    sellerType: "Business",
    sellerName: "Fufu Palace",
    sellerId: "6456a1b2c3d4e5f678901239",
  },
  {
    name: "Banku with Okro Stew",
    description: "Banku served with okro stew and crab.",
    price: 30,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Corn Dough", quantity: "2 cups" },
      { name: "Cassava Dough", quantity: "1 cup" },
      { name: "Okro", quantity: "10 pieces" },
      { name: "Crab", quantity: "2 pieces" },
    ],
    imageUrl: "https://example.com/banku-okro.jpg",
    preparationTime: 50,
    calories: 450,
    general_rating: 4.5,
    health_rating: 4.2,
    trend_rating: 4.6,
    tags: ["Traditional", "Seafood"],
    sellerType: "Private",
    sellerName: "Banku Delight",
    sellerId: "6456a1b2c3d4e5f678901240",
  },
  {
    name: "Jollof Rice with Beef",
    description: "A classic jollof rice dish served with tender beef.",
    price: 28,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Rice", quantity: "2 cups" },
      { name: "Tomatoes", quantity: "3 large" },
      { name: "Beef", quantity: "500g" },
      { name: "Onions", quantity: "2 medium" },
    ],
    imageUrl: "https://example.com/jollof-beef.jpg",
    preparationTime: 45,
    calories: 460,
    general_rating: 4.9,
    health_rating: 4.6,
    trend_rating: 4.8,
    tags: ["Spicy", "Popular"],
    sellerType: "Business",
    sellerName: "Jollof Express",
    sellerId: "6456a1b2c3d4e5f678901241",
  },
  {
    name: "Fried Plantain with Beans",
    description: "Sweet fried plantain served with beans stew.",
    price: 20,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Plantain", quantity: "3 pieces" },
      { name: "Beans", quantity: "1 cup" },
      { name: "Palm Oil", quantity: "1/2 cup" },
      { name: "Onions", quantity: "1 medium" },
    ],
    imageUrl: "https://example.com/plantain-beans.jpg",
    preparationTime: 35,
    calories: 380,
    general_rating: 4.4,
    health_rating: 4.2,
    trend_rating: 4.5,
    tags: ["Vegetarian", "Popular"],
    sellerType: "Private",
    sellerName: "Plantain Paradise",
    sellerId: "6456a1b2c3d4e5f678901242",
  },
  {
    name: "Rice Balls with Groundnut Soup",
    description: "Soft rice balls served with groundnut soup and chicken.",
    price: 32,
    category: "Main Course",
    availability: true,
    ingredients: [
      { name: "Rice", quantity: "2 cups" },
      { name: "Groundnut Paste", quantity: "1 cup" },
      { name: "Chicken", quantity: "500g" },
      { name: "Tomatoes", quantity: "3 large" },
    ],
    imageUrl: "https://example.com/riceballs-groundnut.jpg",
    preparationTime: 60,
    calories: 480,
    general_rating: 4.8,
    health_rating: 4.5,
    trend_rating: 4.9,
    tags: ["Traditional", "Soup"],
    sellerType: "Business",
    sellerName: "Rice Haven",
    sellerId: "6456a1b2c3d4e5f678901243",
  },
  // Add more dishes as needed
  ];

  try {

    console.log("Populating meals table with Ghanaian dishes...");
    await Meals.insertMany(ghanaianDishes);
    console.log("Successfully populated the meals table with Ghanaian dishes.");
    return 250
  } catch (error) {
    console.error("Error populating meals table:", error);
    return 500
  }
}

//populateMeals();

module.exports = { populateMeals };